### ISSUE TITLE
Allow properties like "onsale" to have an end date

### ISSUE THREAD

**Issue by cramforce** [jsconf/jsconf.com-2.0#8]
That way things would automatically be correct once a sale expires. The same would be cool for call for speakers.

**Comment by guahanweb** [comment]
Completely agree. I'd like to see this idea expanded to have a date range, so we can actually configure them in advance and the nightly site build can pick them up once we enter the date range. I'd propose something as simple as this for data structure:

```yaml
jsconfeu:
  status:
    - onsale:
        start: [date]
        end: [date]
```
